### PR TITLE
Add environment variable expansion to user mapping JSON

### PR DESCRIPTION
**Pull request by rhiaxion**
Add environment variable expansion to the user mapping JSON object.

This allows users to provide a JSON user mapping dynamically through environment variables.

Example:
```yaml
steps:
- name: Slack Blame
  image: plugins/slack-blame
  environment:
    SLACK_USER: username
  settings:
    mapping: "{\"$DRONE_COMMIT_AUTHOR\": \"$SLACK_USER\"}"
```

Using the Drone environment extension it's possible to automatically lookup the commit author's slack name and inject it as an env var to the build. This avoids the need for long user maps added to each build.

### CODE REVIEW

**Review by ShiftedMr — APPROVED** [review]

**Comment by rhiaxion** [comment]
@donny-dont could you take a look at this change?

**Comment by tphoney** [comment]
this looks good, but it would be good to have this documented in https://github.com/drone/drone-plugin-index for the slack blame. so if anyone was expecting raw text of "$foo" and not interpolated.

**Review by tphoney — APPROVED** [review]

**Comment by tphoney** [comment]
thanks for the change @rhiaxion merging

**Comment by rhiaxion** [comment]
> this looks good, but it would be good to have this documented in https://github.com/drone/drone-plugin-index for the slack blame. so if anyone was expecting raw text of "$foo" and not interpolated.

@tphoney https://github.com/drone/drone-plugin-index/pull/379
Most of the values are incorrectly marked as required and without default values. Not sure who should handle updating the defaults.

**Comment by tphoney** [comment]
if you add the, warning. i will fix up the rest of the params on your PR. 
if that is ok

**Comment by rhiaxion** [comment]
That would be great, thank you.
Just to confirm, do you want the word `warning` added to the description? So far it looks like this:
```
description: Mapping of authors to Slack users. Supports environment variable interpolation, e.g. {"$DRONE_COMMIT_AUTHOR": "$SLACK_USER"}.
```

**Comment by tphoney** [comment]
that looks good, and then showing what it will look like in the slack message.

**Pull request merged**
