### PR TITLE
Set TitleLink to Drone build link

### PR DESCRIPTION
**Pull request by jesselang**
I think most users would want to go to the Drone build link rather than the commit link on the SCM server. Otherwise, perhaps the link should be a plugin parameter?

### CODE REVIEW

**Comment by josmo** [comment]
@jesselang I tend to agree :) @tboerger @donny-dont thoughts? Otherwise I'll bring it in. Every time I click on the link I get annoyed because I'm expecting the build :)

**Comment by donny-dont** [comment]
@tboerger @bradrydzewski is there any way with notification plugins that we expand the template lib to maybe have code to populate the part of https://github.com/drone-plugins/drone-slack-blame/blob/master/main.go#L83-L97 and the creation of the structs so we can always have all the keys in the same manner across all notification plugins?

This PR is fine I'm just thinking in terms of consistency.

**Comment by tboerger** [comment]
We could predefine the typical template flags as part of the template lib.

**Comment by jesselang** [comment]
Seems this hasn't got traction, so I'll close it out.

**Pull request closed without merging**
